name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      load-test-enabled: false
      trivy-fs-enabled: true
      trivy-image-config: "trivy.yaml"
      zap-enabled: false
      provider: lxd
