name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - 5/main
    paths-ignore:
      - 'docs/**'

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    secrets: inherit
    with:
      channel: 5/edge
