name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - 5/main

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@feat/use_default_branch_as_base_branch
    secrets: inherit
    with:
      channel: 5/edge
