# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Terraform modules compliance

on:
  pull_request:
    paths:
      - '**/terraform/**'

permissions:
  contents: read

jobs:
  terraform-compliance:
    uses: canonical/operator-workflows/.github/workflows/terraform_modules_compliance.yaml@5f7c5ae8edce88c84ce33ac9674995fa551e3e75  # main
    with:
      terraform-directories: '["terraform"]'
