# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Terraform modules compliance

on:
  pull_request:
    paths:
      - '**/terraform/**'

permissions:
  contents: read

jobs:
  terraform-compliance:
    uses: canonical/operator-workflows/.github/workflows/terraform_modules_compliance.yaml@5676f399b24b23385c1cf50867997e15226e8ad3  # main
    with:
      terraform-directories: '["terraform"]'
