# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: Terraform modules release

on:
  workflow_dispatch:
  push:
    branches:
      - 5/main
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform_modules_release.yaml'

jobs:
  terraform:
    uses: canonical/operator-workflows/.github/workflows/terraform_modules_release.yaml@030c5b20a0bb880dcf1ed326bff0fc16b6eb6ac1  # main
    permissions:
      contents: write
