name: Tests

on:
  pull_request:

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@feat/gatekeeper_base_branch
    secrets: inherit
    with:
      base_branch: 5/main
